### ISSUE TITLE
Force APT to use IPv4

### ISSUE THREAD

**Issue by cebe** [cebe-cc/salt-basic#1]
Seems debian mirrors (at least the security one) are very slow on IPv6. Seen this on hetzner cloud, package states are taking a really long time to install. The reason may be as described here:

https://unix.stackexchange.com/questions/9940/convince-apt-get-not-to-use-ipv6-method

Add the following config to ensure IPv4 connection when downloading APT packages:

    echo 'Acquire::ForceIPv4 "true";' | tee /etc/apt/apt.conf.d/99force-ipv4

**Comment by Insolita** [comment]
is it still actual?

**Comment by cebe** [comment]
proabably not, closing it for now.
